name: 'JUnit Test Report for Go Monorepo'
description:
  This action generates a JUnit test report for a Go monorepo with multiple
  go.mod files.

author: 'tapih'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  github-token:
    description: 'The GitHub token to use for authentication'
    required: true
  filename:
    description: 'The filename of the JUnit test report'
    required: true
  pull-request-number:
    description: 'The pull request number to comment on'
    required: true
  sha:
    description: 'The commit SHA to comment on'
    required: true
  limit-failures:
    description: 'The maximum number of failures to display'
    required: true
    default: '30'

outputs:
  body:
    description: 'The body of the comment'

runs:
  using: node20
  main: dist/index.js
