name: 'JUnit Test Report for Go Monorepo'
description: |
  This action generates a JUnit test report for a Go monorepo.
  It expects that the repository has multiple Go modules and JUnit test are
  generated for each module.

  ```
  go
  ├── app1
  │   ├── go.mod
  │   └── junit.xml
  ├── app2
  │   ├── go.mod
  │   └── junit.xml
  └── app3
      ├── go.mod
      └── junit.xml
  ```

author: 'tapih'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  github-token:
    description: 'The GitHub token to use for authentication'
    required: true
  filename:
    description: 'The filename of the JUnit test report'
    required: true
    default: 'junit.xml'

runs:
  using: node20
  main: dist/index.js
