name: 'JUnit Test Report for Go Monorepo'
description:
  This action generates a JUnit test report for a Go monorepo with multiple
  go.mod files.

author: 'tapih'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  github-token:
    description: 'The GitHub token to use for authentication'
    required: true
  config:
    description: |
      YAML-style configuration to define how to parse the test and lint reports (See [JSON schema](./schema.json) for details)
    required: true
  pull-request-number:
    description: |
      The pull request number to comment on

      On `pull_request` events, this input is automatically filled with `github.event.pull_request.number`.
      On `push` events, this action does not make any comment if this input is not provided exciplicitly.
    required: false
  sha:
    description: |
      The commit SHA to comment on

      On `pull_request` events, this input is automatically filled with `github.event.pull_request.head.sha`.
      On `push` events, this input is automatically filled with `github.sha`.
    required: false

outputs:
  body:
    description: 'The body of the comment'

runs:
  using: node20
  main: dist/index.js
