name: 'JUnit Test Report for Go Monorepo'
description:
  This action generates a JUnit test report for a Go monorepo with multiple
  go.mod files.

author: 'tapih'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  github-token:
    description: 'The GitHub token to use for authentication'
    required: true
  test-dirs:
    description:
      The directories that contain the gotestsum reports (seperated by
      commas/spaces/line breaks)
    required: true
  test-report-xml:
    description: The filename of the gotestsum report
    required: true
    default: 'test.xml'
  lint-dirs:
    description:
      The comma-seperated directories that contain the golangci-lint reports
      (seperated by commas/spaces/line breaks)
    required: true
  lint-report-xml:
    description: The filename of the golangci-lint report
    required: true
    default: 'lint.xml'
  pull-request-number:
    description: 'The pull request number to comment on'
    required: true
  sha:
    description: 'The commit SHA to comment on'
    required: true
  failed-test-limit:
    description: 'The maximum number of failed tests to display'
    required: true
    default: '30'
  failed-lint-limit:
    description: 'The maximum number of failed lints to display'
    required: true
    default: '30'

outputs:
  body:
    description: 'The body of the comment'

runs:
  using: node20
  main: dist/index.js
