/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigSchema {
  /**
   * List of columns
   */
  items: {
    /**
     * The name of the column
     */
    title: string
    /**
     * Arbitrary URL attached to the column title
     */
    link?: string
    /**
     * The name of the provider
     */
    provider: 'gotestsum' | 'golangci-lint'
    /**
     * The name of the report file
     */
    report: string
    /**
     * Comma-separated list of paths that may contain a file of which name is equal to "report"
     */
    targets: string
  }[]
}
