name: Transpile

on:
  pull_request:
    branches:
      - main

jobs:
  codegen:
    name: Generate
    if: github.actor != vars.BOT_USERNAME && github.actor != vars.APP_NAME_TAGPR
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Fetch GitHub App Token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: token
        with:
          app-id: ${{ vars.APP_ID_TAGPR }}
          private-key: ${{ secrets.PRIVATE_KEY_TAGPR }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.token.outputs.token }}

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Build dist/ Directory
        id: build
        run: npm run bundle

      - name: Generate Code
        id: generate
        run: npm run generate

      - name: Check diff
        id: diff
        continue-on-error: true
        run: git diff --exit-code

      - name: Push
        env:
          BOT_EMAIL: ${{ vars.BOT_EMAIL }}
          BOT_USERNAME: ${{ vars.BOT_USERNAME }}
        if:
          github.event_name == 'pull_request' && steps.diff.outcome == 'failure'
        run: |
          git config --global user.email "${BOT_EMAIL}"
          git config --global user.name "${BOT_USERNAME}"
          git commit -am "chore: generate code"
          git push
