name: Transpile JavaScript

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  codegen:
    name: Generate
    if: github.actor != vars.BOT_USERNAME
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Fetch GitHub App Token
        uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ vars.APP_ID_TAGPR }}
          private-key: ${{ secrets.PRIVATE_KEY_TAGPR }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref:
            ${{ github.event == 'pull_request' && github.head_ref || github.sha
            }}
          token: ${{ steps.token.outputs.token }}

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Build dist/ Directory
        id: build
        run: npm run bundle

      - name: Generate Code
        id: generate
        run: npm run generate

      - name: Check diff
        id: diff
        continue-on-error: true
        run: git diff --exit-code

      - name: Push
        env:
          BOT_EMAIL: ${{ vars.BOT_EMAIL }}
          BOT_USERNAME: ${{ vars.BOT_USERNAME }}
        if: github.event == 'pull_request' && steps.diff.outcome == 'failure'
        run: |
          git config --global user.email "${BOT_EMAIL}"
          git config --global user.name "${BOT_USERNAME}"
          git commit -am "chore: generate code"
          git push
