name: Tagpr
on:
  push:
    branches:
      - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: {}
    steps:
      - name: Fetch GitHub App Token
        uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ vars.APP_ID_TAGPR }}
          private-key: ${{ secrets.PRIVATE_KEY_TAGPR }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.token.outputs.token }}

      - name: Tagpr
        id: tagpr
        uses: tapihdev/actionshub/Songmu/tagpr@main
        with:
          github-token: ${{ steps.token.outputs.token }}

      - name: Annotate major and minor tags
        if: steps.tagpr.outputs.tag != ''
        uses: tapihdev/tag-major-minor-semver@v1
        with:
          tag: ${{ steps.tagpr.outputs.tag }}
