name: Tagpr
on:
  push:
    branches:
    - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: {}
    steps:
      - uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ vars.APP_ID_TAGPR }}
          private-key: ${{ secrets.PRIVATE_KEY_TAGPR }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.token.outputs.token }}

      - name: Tagpr
        id: tagpr
        uses: tapihdev/actionshub/Songmu/tagpr@main
        with:
          github-token: ${{ steps.token.outputs.token }}

      - name: Annotate major and minor tags
        if: steps.tagpr.outputs.tag != ''
        uses: ./
        with:
          tag: ${{ steps.tagpr.outputs.tag }}
